language: python

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
  - "pip install coverage"
  - "pip install ."

script:
  - "coverage run --source ./ setup.py test"

after_success:
  - "codecov"
